#spring:
#  application:
#    name: data-multidatasource
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://103.50.253.167:3306/test?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 941108
#  second-datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://103.50.253.167:3306/db2?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 941108
server:
  port: 8888
mybatis:
  config-location: classpath:mybatis_config.xml
logging:
  config: classpath:logback.xml
hello:
  msg: world

spring:
  datasource:
    test1:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://103.50.253.167:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 941108
    test2:
      driverClassName:
      jdbcUrl: jdbc:mysql://103.50.253.167:3306/db1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 941108
endpoints:
  beans:
    enabled: true